# Generated by Django 3.2.1 on 2021-05-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='DVD',
        ),
    ]
